[options]
    colorscheme = "gruvbox"
    background = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    textwidth = 100
    colorcolumn = 100

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 20

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#haskell'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#bash'

[[layers]]
name = 'lang#ruby'

[[layers]]
name = 'lang#rust'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#java'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#yaml'

