[options]
    colorscheme = "gruvbox"
    background = "dark"
    enable_guicolors = false
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    textwidth = 100
    colorcolumn = 100

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 20

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'fzf'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'git'

[[layers]]
name = 'tmux'

[[layers]]
name = 'vim-multiple-cursors'

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#haskell'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#ruby'

[[layers]]
name = 'lang#rust'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#typescript'

[[layers]]
name = 'lang#java'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#charp'

[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = 'lang#vim'

[[layers]]
name = 'lang#tmux'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#json'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#yaml'

[[layers]]
name = 'lang#xml'

[[layers]]
name = 'lang#html'
